spool cr_tab_DWHEVO_RSK_DM_ANDINT_CONTICORRENTI.log

WHENEVER OSERROR  EXIT 9;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
SET SERVEROUTPUT ON
SET TIMING ON

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"';
dbms_output.put_line('Cancellata tabella "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI".');
EXCEPTION
WHEN OTHERS THEN
dbms_output.put_line('Nuova tabella "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI".');
END;
/

CREATE TABLE DWHEVO.RSK_DM_ANDINT_CONTICORRENTI
(	
	COD_ABI						VARCHAR2(5),
	COD_CAG						VARCHAR2(11),
	CAG_GRUPPO_CCB              VARCHAR2(11),
	COD_SERVIZIO				VARCHAR2(3),
	COD_RAPPORTO				VARCHAR2(11),
	DATA_RIFERIMENTO			DATE,
	MFT                         VARCHAR2(255),
	TIPO_CONTO_CORRENTE			CHAR(1),
    FLAG_CC_PASSIVO             NUMBER,
	ACCORDATO_OPERATIVO 		NUMBER,
	NUM_GG_SCONFINO				NUMBER,
	NUM_MAX_GG_SCONF_CONSEC 	NUMBER,
	SALDO_CONTABILE 			NUMBER,
	SALDO_LIQUIDO_MEDIO_AVERE 	NUMBER,
	UTILIZZATO					NUMBER,
	SALDO_LIQUIDO_MEDIO_DARE 	NUMBER,
	SALDO_MEDIO_CONTABILE_A 	NUMBER,
	SALDO_MEDIO_CONTABILE_D 	NUMBER,
	DATA_APERTURA_RAPPORTO      DATE,
	DATA_ESTINZIONE_RAPPORTO    DATE,
	divisa 						varchar2(3)
	CONSTRAINT "PK_CONTICORRENTI" PRIMARY KEY ("COD_ABI","COD_CAG","COD_SERVIZIO","COD_RAPPORTO","DATA_RIFERIMENTO") using index local -- vedi last update
)
ROW STORE COMPRESS ADVANCED
TABLESPACE "DWHEVO_DATA_04" 
PARTITION BY LIST ("DATA_RIFERIMENTO","COD_ABI") AUTOMATIC 
(	PARTITION "RSK_DM_CONTICORRENTI_DEFAULT_PARTITION"  VALUES (( TO_DATE(' 2021-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'), '00000' ))
	PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	STORAGE(
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DWHEVO_DATA_04"
);

COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."COD_ABI" IS 'Codice identificativo del soggetto (abi)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."COD_CAG" IS 'Codice identificativo del soggetto (ndg)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."CAG_GRUPPO_CCB" IS 'Codice identificativo del soggetto (ndg)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."COD_RAPPORTO" IS 'Chiave di sintesi del partitario con ABI, NDG, DATA_RIFERIMENTO';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."MFT" IS 'Macro Forma Tecnica';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."TIPO_CONTO_CORRENTE" IS 'Tipo Conto Corrente';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."FLAG_CC_PASSIVO" IS 'Flag Conto Corrente Passivo';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."ACCORDATO_OPERATIVO" IS 'Accordato Operativo';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."NUM_GG_SCONFINO" IS 'E il numero di giorni di sconfinamento al mese, calcolabile effettuando una Count dei record relativi al rapporto nell arco temporale del mese di riferimento';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."NUM_MAX_GG_SCONF_CONSEC" IS 'Numero Massimo di Giorni di Sconfinamento';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."SALDO_CONTABILE" IS 'Saldo Contabile';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."SALDO_LIQUIDO_MEDIO_AVERE" IS 'Saldo Liquido Medio Avere';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."UTILIZZATO" IS 'Utilizzato';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."SALDO_LIQUIDO_MEDIO_DARE" IS 'Saldo liquido medio dare di periodo';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."SALDO_MEDIO_CONTABILE_A" IS 'Saldo medio contabile avere del Rapporto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."SALDO_MEDIO_CONTABILE_D" IS 'Saldo medio contabile dare del Rapporto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."DATA_APERTURA_RAPPORTO" IS 'Data Apertura Rapporto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI"."DATA_ESTINZIONE_RAPPORTO" IS 'Data Estinzione Rapporto';

GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI" TO "DATAMARTRATING" WITH GRANT OPTION;
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI" TO "DWHEVO_READ_ROLE";
GRANT DELETE ON "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI" TO "DWHEVO_WRITE_ROLE";
GRANT INSERT ON "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI" TO "DWHEVO_WRITE_ROLE";
GRANT UPDATE ON "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI" TO "DWHEVO_WRITE_ROLE";
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_CONTICORRENTI" TO "TFACT";

CREATE OR REPLACE SYNONYM DWHEVO.RSK_DM_ANDINT_CONTICORRENTI_SYN FOR DWHEVO.RSK_DM_ANDINT_CONTICORRENTI;

spool off
