spool cr_tab_DWHEVO_RSK_DM_ANDINT_DEPOSITOTITOLI.log

WHENEVER OSERROR  EXIT 9;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
SET SERVEROUTPUT ON
SET TIMING ON

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI"';
dbms_output.put_line('Cancellata tabella "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI".');
EXCEPTION
WHEN OTHERS THEN
dbms_output.put_line('Nuova tabella "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI".');
END;
/

CREATE TABLE DWHEVO.RSK_DM_ANDINT_DEPOSITOTITOLI
(	
	COD_ABI				VARCHAR2(5),
	COD_CAG				VARCHAR2(11),
	CAG_GRUPPO_CCB		VARCHAR2(11),
	COD_SERVIZIO		VARCHAR2(3),
	COD_RAPPORTO		VARCHAR2(11),
	DATA_RIFERIMENTO	DATE,
	SALDO_IAS 			NUMBER,
	MFT					VARCHAR2(255),				   
	CONTROVALORE_TITOLI NUMBER,
	FLAG_PRODOTTO 		VARCHAR2(9),
	FT_PRODOTTO			VARCHAR2(255),						 
	CONSTRAINT "PK_DEPOSITOTITOLI" PRIMARY KEY ("COD_ABI","COD_CAG","COD_SERVIZIO","DATA_RIFERIMENTO", "COD_RAPPORTO") using index local
)
ROW STORE COMPRESS ADVANCED
TABLESPACE "DWHEVO_DATA_06" 
PARTITION BY LIST ("DATA_RIFERIMENTO","COD_ABI") AUTOMATIC 
(	PARTITION "RSK_DM_DEPOSITOTITOLI_DEFAULT_PARTITION"  VALUES (( TO_DATE(' 2021-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'), '00000' ))
	PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	STORAGE(
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DWHEVO_DATA_06"
);

COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI"."COD_ABI" IS 'Codice identificativo del soggetto (abi)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI"."COD_CAG" IS 'Codice identificativo del soggetto (ndg)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI"."COD_RAPPORTO" IS 'Chiave di sintesi del partitario con ABI, NDG, DATA_RIFERIMENTO';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI"."MFT" IS 'Macro Forma Tecnica';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI"."SALDO_IAS" IS 'SALDO IAS';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI"."CONTROVALORE_TITOLI" IS 'Controvalore dei titoli';


GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI" TO "DATAMARTRATING" WITH GRANT OPTION;
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI" TO "DWHEVO_READ_ROLE";
GRANT DELETE ON "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI" TO "DWHEVO_WRITE_ROLE";
GRANT INSERT ON "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI" TO "DWHEVO_WRITE_ROLE";
GRANT UPDATE ON "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI" TO "DWHEVO_WRITE_ROLE";
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_DEPOSITOTITOLI" TO "TFACT";

CREATE OR REPLACE SYNONYM DWHEVO.RSK_DM_ANDINT_DEPOSITOTITOLI_SYN FOR DWHEVO.RSK_DM_ANDINT_DEPOSITOTITOLI;

spool off
