spool cr_tab_DWHEVO_RSK_DM_ANDINT_FONDIESICAV.log

WHENEVER OSERROR  EXIT 9;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
SET SERVEROUTPUT ON
SET TIMING ON

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV"';
dbms_output.put_line('Cancellata tabella "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV".');
EXCEPTION
WHEN OTHERS THEN
dbms_output.put_line('Nuova tabella "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV".');
END;
/

CREATE TABLE DWHEVO.RSK_DM_ANDINT_FONDIESICAV
(	
	COD_ABI		 			VARCHAR2(5)
	,COD_CAG				VARCHAR2(11)
	,CAG_GRUPPO_CCB			VARCHAR2(11)
	,COD_SERVIZIO			VARCHAR2(3)
	,COD_RAPPORTO			VARCHAR2(11)
	,DATA_RIFERIMENTO		DATE
	,FT_PRODOTTO			VARCHAR2(255)
	,CODICE_ISIN			VARCHAR2(11)
	,IMP_CONTROV_SECCO_EUR 	NUMBER
	,CONSTRAINT "PK_FONDIESICAV" PRIMARY KEY ("COD_ABI","COD_CAG","COD_SERVIZIO","COD_RAPPORTO","DATA_RIFERIMENTO","CODICE_ISIN") using index local
)
ROW STORE COMPRESS ADVANCED
TABLESPACE "DWHEVO_DATA_02" 
PARTITION BY LIST ("DATA_RIFERIMENTO","COD_ABI") AUTOMATIC 
(	PARTITION "RSK_DM_FONDIESICAV_DEFAULT_PARTITION"  VALUES (( TO_DATE(' 2021-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'), '00000' ))
	PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	STORAGE(
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DWHEVO_DATA_02"
);

COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV"."COD_ABI" IS 'Codice identificativo del soggetto (abi)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV"."CODICE_ISIN" IS 'Codice fondo (ISIN)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV"."IMP_CONTROV_SECCO_EUR" IS 'Importo Controvalore Fondo';

GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV" TO "DATAMARTRATING" WITH GRANT OPTION;
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV" TO "DWHEVO_READ_ROLE";
GRANT DELETE ON "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV" TO "DWHEVO_WRITE_ROLE";
GRANT INSERT ON "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV" TO "DWHEVO_WRITE_ROLE";
GRANT UPDATE ON "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV" TO "DWHEVO_WRITE_ROLE";
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_FONDIESICAV" TO "TFACT";

CREATE OR REPLACE SYNONYM DWHEVO.RSK_DM_ANDINT_FONDIESICAV_SYN FOR DWHEVO.RSK_DM_ANDINT_FONDIESICAV;

spool off