spool cr_tab_DWHEVO_RSK_DM_ANDINT_CREDITIDIFIRMA.log

WHENEVER OSERROR  EXIT 9;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
SET SERVEROUTPUT ON
SET TIMING ON


BEGIN
EXECUTE IMMEDIATE 'DROP TABLE "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"';
dbms_output.put_line('Cancellata tabella "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA".');
EXCEPTION
WHEN OTHERS THEN
dbms_output.put_line('Nuova tabella "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA".');
END;
/

CREATE TABLE DWHEVO.RSK_DM_ANDINT_CREDITIDIFIRMA 
(	
	COD_ABI					VARCHAR2(5),
	COD_CAG					VARCHAR2(11),
	CAG_GRUPPO_CCB			VARCHAR2(11),
	COD_SERVIZIO			VARCHAR2(3),
	COD_RAPPORTO			VARCHAR2(11),
	DATA_RIFERIMENTO		DATE,
	MFT						VARCHAR2(255),
	UTILIZZATO_FIRMA 		NUMBER,
	FIDO_OPERATIVO_FIRMA	NUMBER,
	DATA_ACCENSIONE_RAPP	DATE,
	DATA_SCADENZA_RAPP		DATE,
	COD_RAPP_PARTITA		NUMBER,
	DATA_ESTINZIONE_RAPP	DATE,
	CONSTRAINT "PK_CREDITIDIFIRMA" PRIMARY KEY ("COD_ABI","COD_CAG","COD_SERVIZIO","COD_RAPPORTO","DATA_RIFERIMENTO","COD_RAPP_PARTITA") using index local
)
ROW STORE COMPRESS ADVANCED
TABLESPACE "DWHEVO_DATA_09" 
PARTITION BY LIST ("DATA_RIFERIMENTO","COD_ABI") AUTOMATIC 
(	PARTITION "RSK_DM_CREDITIDIFIRMA_DEFAULT_PARTITION"  VALUES (( TO_DATE(' 2021-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'), '00000' ))
	PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	STORAGE(
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DWHEVO_DATA_09"
);

COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."COD_ABI" IS 'Codice identificativo del soggetto (abi)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."COD_CAG" IS 'Codice identificativo del soggetto (ndg)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."COD_RAPPORTO" IS 'Chiave di sintesi del partitario con ABI, NDG, DATA_RIFERIMENTO';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."MFT" IS 'Macro Forma Tecnica';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."UTILIZZATO_FIRMA" IS 'Utilizzo firma';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."FIDO_OPERATIVO_FIRMA" IS 'Fido operativo firma';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."DATA_ACCENSIONE_RAPP" IS 'Data di accensione del rapporto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."DATA_SCADENZA_RAPP" IS 'Data di scadenza del rapporto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."COD_RAPP_PARTITA" IS 'ID Partita';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA"."DATA_ESTINZIONE_RAPP" IS 'Data Estinzione del Rapporto';

GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA" TO "DATAMARTRATING" WITH GRANT OPTION;
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA" TO "DWHEVO_READ_ROLE";
GRANT DELETE ON "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA" TO "DWHEVO_WRITE_ROLE";
GRANT INSERT ON "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA" TO "DWHEVO_WRITE_ROLE";
GRANT UPDATE ON "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA" TO "DWHEVO_WRITE_ROLE";
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_CREDITIDIFIRMA" TO "TFACT";

CREATE OR REPLACE SYNONYM DWHEVO.RSK_DM_ANDINT_CREDITIDIFIRMA_SYN FOR DWHEVO.RSK_DM_ANDINT_CREDITIDIFIRMA;

spool off