spool cr_tab_DWHEVO_RSK_DM_ANDINT_RATEALI.log 

WHENEVER OSERROR  EXIT 9;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
SET SERVEROUTPUT ON
SET TIMING ON

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE "DWHEVO"."RSK_DM_ANDINT_RATEALI"';
dbms_output.put_line('Cancellata tabella "DWHEVO"."RSK_DM_ANDINT_RATEALI".');
EXCEPTION
WHEN OTHERS THEN
dbms_output.put_line('Nuova tabella "DWHEVO"."RSK_DM_ANDINT_RATEALI".');
END;
/

CREATE TABLE DWHEVO.RSK_DM_ANDINT_RATEALI 
(	
	COD_ABI								VARCHAR2(5),
	COD_CAG								VARCHAR2(11),
	CAG_GRUPPO_CCB					    VARCHAR2(11),
	COD_SERVIZIO						VARCHAR2(3),
	COD_RAPPORTO						VARCHAR2(11),
	DATA_RIFERIMENTO					DATE,
	MFT                                 VARCHAR2(255),
	QUOTA_INTERESSI_RATE_SCAD_MORA 		NUMBER,
	QUOTA_INTERESSI_RATE_SCAD_IMPAGA	NUMBER,
	QUOTA_CAPITALE_RATE_SCAD_MORA 		NUMBER,
	QUOTA_CAPITALE_RATE_SCAD_IMPAGAT	NUMBER,
	NUMERO_RATE_MORA 					NUMBER,
	NUMERO_RATE_IMPAGATE 				NUMBER,
	IMP_RATE_IMPAGATE 					NUMBER,
	FIDO_OPERAT_CONTAB 					NUMBER,
	FIDO_RESIDUO 						NUMBER,
	IMP_ORIG_FIDO 						NUMBER,
	IMP_RATE_MORA 						NUMBER,
	IMP_ULTIMA_RATA_SCAD 				NUMBER,
	UTILIZZATO_CONTAB 					NUMBER,
	UTILIZZATO 							NUMBER,
	TIPO_PRODOTTO 						VARCHAR2(8 CHAR),
	DATA_ACCENSIONE_RAPP                DATE,
	DATA_SCADENZA_RAPP                  DATE,
	PERIODICITA_RATA                    VARCHAR2(2),
	DATA_ESTINZIONE_RAPP                DATE,
	FLAG_IPOTECARIO_S_N					VARCHAR2(1),
	CONSTRAINT "PK_RATEALI" PRIMARY KEY ("COD_ABI","COD_CAG","COD_SERVIZIO","COD_RAPPORTO","DATA_RIFERIMENTO") using index local
)
ROW STORE COMPRESS ADVANCED
TABLESPACE "DWHEVO_DATA_05" 
PARTITION BY LIST ("DATA_RIFERIMENTO","COD_ABI") AUTOMATIC 
(	PARTITION "RSK_DM_RATEALI_DEFAULT_PARTITION"  VALUES (( TO_DATE(' 2021-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'), '00000' ))
	PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	STORAGE(
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DWHEVO_DATA_05"
);

COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."COD_ABI" IS 'Codice identificativo del soggetto (abi)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."COD_CAG" IS 'Codice identificativo del soggetto (ndg)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."COD_RAPPORTO" IS 'Chiave di sintesi del partitario con ABI, NDG, DATA_RIFERIMENTO';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."MFT" IS 'Macro Forma Tecnica';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."QUOTA_INTERESSI_RATE_SCAD_MORA" IS 'Quota interessi rate scadute in mora';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."QUOTA_INTERESSI_RATE_SCAD_IMPAGA" IS 'Quota interessi rate scadute insolute';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."QUOTA_CAPITALE_RATE_SCAD_MORA" IS 'Quota capitale rate scadute in mora';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."QUOTA_CAPITALE_RATE_SCAD_IMPAGAT" IS 'Quota capitale rate scadute insolute';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."NUMERO_RATE_MORA" IS 'Numero rate in mora';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."NUMERO_RATE_IMPAGATE" IS 'Numero rate insolute';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."IMP_RATE_IMPAGATE" IS 'Importo rate insolute';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."FIDO_OPERAT_CONTAB" IS 'Fido Operativo Contabile';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."FIDO_RESIDUO" IS 'Fido residuo (Capitale)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."IMP_ORIG_FIDO" IS 'Importo originario del fido (Capitale)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."IMP_RATE_MORA" IS 'Importo rate in mora';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."IMP_ULTIMA_RATA_SCAD" IS 'Importo ultima rata in scadenza';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."UTILIZZATO_CONTAB" IS 'Utilizzo contabile';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."UTILIZZATO" IS 'Utilizzato (Capitale)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."TIPO_PRODOTTO" IS 'Tipo prodotto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."DATA_ACCENSIONE_RAPP" IS 'Data Accensione Rapporto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."DATA_SCADENZA_RAPP" IS 'Data di scadenza del rapporto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."PERIODICITA_RATA" IS 'Periodicità della rata';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_RATEALI"."DATA_ESTINZIONE_RAPP" IS 'Data Estinzione del Rapporto';

GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_RATEALI" TO "DATAMARTRATING" WITH GRANT OPTION;
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_RATEALI" TO "DWHEVO_READ_ROLE";
GRANT DELETE ON "DWHEVO"."RSK_DM_ANDINT_RATEALI" TO "DWHEVO_WRITE_ROLE";
GRANT INSERT ON "DWHEVO"."RSK_DM_ANDINT_RATEALI" TO "DWHEVO_WRITE_ROLE";
GRANT UPDATE ON "DWHEVO"."RSK_DM_ANDINT_RATEALI" TO "DWHEVO_WRITE_ROLE";
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_RATEALI" TO "TFACT";

CREATE OR REPLACE SYNONYM DWHEVO.RSK_DM_ANDINT_RATEALI_SYN FOR DWHEVO.RSK_DM_ANDINT_RATEALI;

spool off