spool cr_tab_DWHEVO_RSK_DM_ANDINT_ANTICIPIEFACTORING.log

WHENEVER OSERROR  EXIT 9;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
SET SERVEROUTPUT ON
SET TIMING ON

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"';
dbms_output.put_line('Cancellata tabella "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING".');
EXCEPTION
WHEN OTHERS THEN
dbms_output.put_line('Nuova tabella "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING".');
END;
/

CREATE TABLE DWHEVO.RSK_DM_ANDINT_ANTICIPIEFACTORING 
(	
	COD_ABI								VARCHAR2(5),
	COD_CAG								VARCHAR2(11),
	CAG_GRUPPO_CCB   					VARCHAR2(11),
	COD_SERVIZIO						VARCHAR2(3),
	COD_RAPPORTO						VARCHAR2(11),
	DATA_RIFERIMENTO					DATE,
	MFT                                 VARCHAR2(255),
	NUM_MASSIVO_GG_SCONF_CONS 			NUMBER,
	NUM_FATTURE_STORNATE 				NUMBER,
	NUM_FATTURE_SCADUTE 				NUMBER,
	NUM_FATTURE_PROROGATE 				NUMBER,
	NUM_DISTINTE_PRESENTATE 			NUMBER,
	IMP_ANTICIPATO_FATT_STORNATE 		NUMBER,
	IMP_ANTICIPATO_FATT_SCADUTE 		NUMBER,
	IMP_ANTICIPATO_FATTURE_PROROGATE	NUMBER,
	IMP_ANTICIPATO_DISTINTE_PRESENTA 	NUMBER,
	UTILIZZATO_CONTABILE 				NUMBER,
	FIDO_OPERATIVO_CONTABILE 			NUMBER,
	DATA_ACCENSIONE_RAPP                DATE,
	DATA_SCADENZA_RAPP                  DATE,
	FLAG_ANTICIPO_ESTERO                VARCHAR2(2),
	FLAG_FINANZIAMENTI_IMPORTAZ         VARCHAR2(8 CHAR),
	DATA_ESTINZIONE_RAPP                DATE,
	CONSTRAINT "PK_ANTICIPIEFACTORING" PRIMARY KEY ("COD_ABI","COD_CAG","COD_SERVIZIO","COD_RAPPORTO","DATA_RIFERIMENTO") using index local
)
ROW STORE COMPRESS ADVANCED
TABLESPACE "DWHEVO_DATA_08" 
PARTITION BY LIST ("DATA_RIFERIMENTO","COD_ABI") AUTOMATIC 
(	PARTITION "RSK_DM_ANTICIPIEFACTORING_DEFAULT_PARTITION"  VALUES (( TO_DATE(' 2021-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'), '00000' ))
	PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	STORAGE(
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DWHEVO_DATA_08"
);

COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."COD_ABI" IS 'Codice identificativo del soggetto (abi)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."COD_CAG" IS 'Codice identificativo del soggetto (ndg)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."CAG_GRUPPO_CCB" IS 'CAG Gruppo CCB';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."COD_RAPPORTO" IS 'Chiave di sintesi del partitario con ABI, NDG, DATA_RIFERIMENTO';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."MFT" IS 'Macro Forma Tecnica';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."NUM_MASSIVO_GG_SCONF_CONS" IS 'Numero massimo di giorni di sconfino consecutivi';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."NUM_FATTURE_STORNATE" IS 'Numero fatture (impagate) stornate';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."NUM_FATTURE_SCADUTE" IS 'Numero fatture scadute (pagate o impagate)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."NUM_FATTURE_PROROGATE" IS 'Numero fatture prorogate (ritardata)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."NUM_DISTINTE_PRESENTATE" IS 'Numero distinte presentate';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."IMP_ANTICIPATO_FATT_STORNATE" IS 'Importo anticipato (impagate) stornate';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."IMP_ANTICIPATO_FATT_SCADUTE" IS 'Importo anticipato fatture scadute (pagate o impagate)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."IMP_ANTICIPATO_FATTURE_PROROGATE" IS 'Importo anticipato fatture prorogate (ritardata)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."IMP_ANTICIPATO_DISTINTE_PRESENTA" IS 'Importo anticipato distinte presentate';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."UTILIZZATO_CONTABILE" IS 'Utilizzo contabile';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."FIDO_OPERATIVO_CONTABILE" IS 'Fido operativo contabile';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."DATA_ACCENSIONE_RAPP" IS 'Data accensione del rapporto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."DATA_SCADENZA_RAPP" IS 'Data Scadenza Rapporto';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."FLAG_ANTICIPO_ESTERO" IS 'Flag Anticipo Estero';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."FLAG_FINANZIAMENTI_IMPORTAZ" IS 'Flag Finanziamenti alle Importazioni';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING"."DATA_ESTINZIONE_RAPP" IS 'Data estinzione del rapporto';

GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING" TO "DATAMARTRATING" WITH GRANT OPTION;
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING" TO "DWHEVO_READ_ROLE";
GRANT DELETE ON "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING" TO "DWHEVO_WRITE_ROLE";
GRANT INSERT ON "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING" TO "DWHEVO_WRITE_ROLE";
GRANT UPDATE ON "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING" TO "DWHEVO_WRITE_ROLE";
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_ANTICIPIEFACTORING" TO "TFACT";

CREATE OR REPLACE SYNONYM DWHEVO.RSK_DM_ANDINT_ANTICIPIEFACTORING_SYN FOR DWHEVO.RSK_DM_ANDINT_ANTICIPIEFACTORING;

spool off
