spool cr_tab_DWHEVO_RSK_DM_ANDINT_MOVASSEGNI.log

WHENEVER OSERROR  EXIT 9;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
SET SERVEROUTPUT ON
SET TIMING ON

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"';
dbms_output.put_line('Cancellata tabella "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI".');
EXCEPTION
WHEN OTHERS THEN
dbms_output.put_line('Nuova tabella "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI".');
END;
/

CREATE TABLE DWHEVO.RSK_DM_ANDINT_MOVASSEGNI 
(	
	COD_ABI						VARCHAR2(5),
	COD_CAG						VARCHAR2(11),
    CAG_GRUPPO_CCB              VARCHAR2(11),
	COD_SERVIZIO				VARCHAR2(3),
	COD_RAPPORTO				VARCHAR2(11),
    DATA_RIFERIMENTO			DATE,
    MFT                         VARCHAR2(255),
	IMPORTO_ASSEGNI_IMPAGATI 	NUMBER,
	IMPORTO_ASSEGNI_PROTESTATI 	NUMBER,
	IMPORTO_ASSEGNI_SOSPESI 	NUMBER,
	IMPORTO_MOVIMENTI_AVERE 	NUMBER,
	IMPORTO_MOVIMENTI_DARE 		NUMBER,
	NUMERO_ASSEGNI_IMPAGATI 	NUMBER,
	NUMERO_ASSEGNI_PROTESTATI 	NUMBER,
	NUMERO_ASSEGNI_SOSPESI 		NUMBER,
	NUMERO_MOVIMENTI_AVERE 		NUMBER,
	NUMERO_MOVIMENTI_DARE 		NUMBER,
	CONSTRAINT "PK_MOVASSEGNI" PRIMARY KEY ("COD_ABI","COD_CAG","COD_SERVIZIO","COD_RAPPORTO","DATA_RIFERIMENTO")using index local
)
ROW STORE COMPRESS ADVANCED
TABLESPACE "DWHEVO_DATA_02" 
PARTITION BY LIST ("DATA_RIFERIMENTO","COD_ABI") AUTOMATIC 
(	PARTITION "RSK_DM_MOVASSEGNI_DEFAULT_PARTITION"  VALUES (( TO_DATE(' 2021-01-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'), '00000' ))
	PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	STORAGE(
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DWHEVO_DATA_02"
);

COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."COD_ABI" IS 'Codice identificativo del soggetto (abi)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."COD_CAG" IS 'Codice identificativo del soggetto (ndg)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."CAG_GRUPPO_CCB" IS 'Codice identificativo del soggetto (ndg)';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."COD_RAPPORTO" IS 'Chiave di sintesi del partitario con ABI, NDG, DATA_RIFERIMENTO';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."MFT" IS 'Macro Forma Tecnica';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."IMPORTO_ASSEGNI_IMPAGATI" IS 'Totale Importo degli assegni impagati';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."IMPORTO_ASSEGNI_PROTESTATI" IS 'Totale Importo degli assegni protestai';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."IMPORTO_ASSEGNI_SOSPESI" IS 'Totale Importo degli assegni sospesi';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."IMPORTO_MOVIMENTI_AVERE" IS 'Importo movimenti avere';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."IMPORTO_MOVIMENTI_DARE" IS 'Importo movimenti dare';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."NUMERO_ASSEGNI_IMPAGATI" IS 'Numero Assegni Impagati';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."NUMERO_ASSEGNI_PROTESTATI" IS 'Numero Assegni Protestati';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."NUMERO_ASSEGNI_SOSPESI" IS 'Numero Assegni Sospesi';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."NUMERO_MOVIMENTI_AVERE" IS 'Numero Movimenti Avere';
COMMENT ON COLUMN "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI"."NUMERO_MOVIMENTI_DARE" IS 'Numero Movimenti Dare';


GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI" TO "DATAMARTRATING" WITH GRANT OPTION;
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI" TO "DWHEVO_READ_ROLE";
GRANT DELETE ON "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI" TO "DWHEVO_WRITE_ROLE";
GRANT INSERT ON "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI" TO "DWHEVO_WRITE_ROLE";
GRANT UPDATE ON "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI" TO "DWHEVO_WRITE_ROLE";
GRANT SELECT ON "DWHEVO"."RSK_DM_ANDINT_MOVASSEGNI" TO "TFACT";

CREATE OR REPLACE SYNONYM DWHEVO.RSK_DM_ANDINT_MOVASSEGNI_SYN FOR DWHEVO.RSK_DM_ANDINT_MOVASSEGNI;

spool off
